### ISSUE TITLE
Unable to find :trellis-reactive when building project

### ISSUE THREAD

**Issue by jholleran** [trellis-ldp/trellis-microprofile#5]
[jholleran-ThinkPad-P52: trellis-microprofile]$ ./gradlew assemble
> Task :trellis-database:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':trellis-database:compileJava'.
> Could not resolve all files for configuration ':trellis-database:compileClasspath'.
   > Could not find org.trellisldp:trellis-reactive:.
     Required by:
         project :trellis-database

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 650ms

**Comment by acoburn** [comment]
The `trellis-reactive` artifact was missing from the `trellis-bom` until last week. See https://github.com/trellis-ldp/trellis/pull/521. Can you check whether your locally-installed `trellis-bom` artifact is up to date? One option is to run this:

```
$ rm -rf ~/.m2/repository/org/trellisldp
```

which will pull down the current snapshot versions.

**Comment by jholleran** [comment]
That worked. Thanks Aaron.
